a.out: indx4.o dynamic_array.o skorowidz.o skorowidz_licznik.o
	$(CC) $^

indx4.o: dynamic_array.h skorowidz.h
skorowidz.o: dynamic_array.h skorowidz.h
dynamic_array.o: dynamic_array.h
skorowidz_licznik.o: skorowidz_licznik.h
